### PR TITLE
Maybe fix tox failing

### PR DESCRIPTION
**Pull request by lmm**
`tox` has been failing on master recently, see: https://tigera.semaphoreci.com/jobs/1cd2d42d-a735-41f0-893c-e7318950495e

Lots of errors like:
```Traceback (most recent call last):02:05
  File "/home/semaphore/networking-calico/.tox/py38/lib/python3.6/site-packages/neutron/tests/base.py", line 398, in setUp02:05
    policy.init()02:05
  File "/home/semaphore/networking-calico/.tox/py38/lib/python3.6/site-packages/neutron/policy.py", line 78, in init02:05
    register_rules(_ENFORCER)02:05
  File "/home/semaphore/networking-calico/.tox/py38/lib/python3.6/site-packages/neutron/policy.py", line 69, in register_rules02:05
    enforcer.register_defaults(itertools.chain(*policies))02:05
  File "/home/semaphore/networking-calico/.tox/py38/lib/python3.6/site-packages/oslo_policy/policy.py", line 1119, in register_defaults02:05
    self.register_default(default)02:05
  File "/home/semaphore/networking-calico/.tox/py38/lib/python3.6/site-packages/oslo_policy/policy.py", line 1108, in register_default02:05
    self.registered_rules[default.name] = copy.deepcopy(default)02:05
  File "/home/semaphore/networking-calico/.tox/py38/lib/python3.6/copy.py", line 180, in deepcopy02:05
    y = _reconstruct(x, memo, *rv)02:05
  File "/home/semaphore/networking-calico/.tox/py38/lib/python3.6/copy.py", line 280, in _reconstruct02:05
    state = deepcopy(state, memo)02:05
  File "/home/semaphore/networking-calico/.tox/py38/lib/python3.6/copy.py", line 150, in deepcopy02:05
    y = copier(x, memo)02:05
  File "/home/semaphore/networking-calico/.tox/py38/lib/python3.6/copy.py", line 240, in _deepcopy_dict02:05
    y[deepcopy(key, memo)] = deepcopy(value, memo)02:05
  File "/home/semaphore/networking-calico/.tox/py38/lib/python3.6/copy.py", line 180, in deepcopy02:05
    y = _reconstruct(x, memo, *rv)02:05
  File "/home/semaphore/networking-calico/.tox/py38/lib/python3.6/copy.py", line 280, in _reconstruct02:05
    state = deepcopy(state, memo)02:05
  File "/home/semaphore/networking-calico/.tox/py38/lib/python3.6/copy.py", line 150, in deepcopy02:05
    y = copier(x, memo)02:05
  File "/home/semaphore/networking-calico/.tox/py38/lib/python3.6/copy.py", line 240, in _deepcopy_dict02:05
    y[deepcopy(key, memo)] = deepcopy(value, memo)02:05
  File "/home/semaphore/networking-calico/.tox/py38/lib/python3.6/copy.py", line 161, in deepcopy02:05
    y = copier(memo)02:05
TypeError: cannot deepcopy this pattern object
```

This PR updates python3 packages for the tox job and updates tox itself. This seems to fix the tests.

### CODE REVIEW

**Comment by lmm** [comment]
@neiljerram could you please take a look to see if these changes are appropriate? I'm not very familiar with python and its ecosystem.

**Review by nelljerram — APPROVED** [review]
Thanks @lmm , it's a nice change anyway.  But - for the record - do you know any more about why using a newer tox fixes the detailed deepcopy problem?

**Comment by lmm** [comment]
> But - for the record - do you know any more about why using a newer tox fixes the detailed deepcopy problem?

I'm not sure. With the newer tox, it uses a newer Python version. E.g. I see logs like this with the newer tox:
```
  File "/home/semaphore/networking-calico/.tox/py38/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
```

I've tried just using a newer Python version with `sem-version python 3.8` and the old tox but I get the same error as in the PR description.

**Comment by nelljerram** [comment]
Thanks @lmm , I'm happy that we've just recorded as much as we know.  No need to dig further, I think.

**Pull request merged**
